const VERSION = "0.0.1";
const NATIVE = {
    BRIDGE_NAME: "_NATIVE_BRIDGE",

    BRIDGE_VERSION: "_version",

    TYPE_CALL: 0,
    TYPE_CALLBACK: 1,

    ACTION_TYPE: "type",
    ACTION_NAME: "name",

    ERROR_STATUS: "status",
    ERROR_MESSAGE: "message",

    RESPONSE_ERROR: "err",
    RESPONSE_DATA: "data",

    LISTENER_NAME: "name"
};
const WEB = {
    BRIDGE_NAME: "_WEB_BRIDGE",

    BRIDGE_VERSION: NATIVE.BRIDGE_VERSION,

    TYPE_CALL: NATIVE.TYPE_CALL,
    TYPE_CALLBACK: NATIVE.TYPE_CALLBACK,

    ACTION_TYPE: NATIVE.ACTION_TYPE,
    ACTION_NAME: NATIVE.ACTION_NAME,

    RESPONSE_ERROR: NATIVE.RESPONSE_ERROR,
    RESPONSE_DATA: NATIVE.RESPONSE_DATA,

    LISTENER_NAME: NATIVE.LISTENER_NAME
};

exports.VERSION = VERSION;
exports.NATIVE = NATIVE;
exports.WEB = WEB;